name: Print GitHub Issues

on:
  issues:
    types: [opened]

jobs:
  print-issue:
    runs-on: ubuntu-latest
    steps:
      - name: Print Issue
        run: |
          curl -X POST https://github-issue-printer.herokuapp.com/api/github-webhook \
            -H "Content-Type: application/json" \
            -d '{"action":"opened","issue":${{ toJSON(github.event.issue) }},"repository":{"full_name":"${{ github.repository }}"}}'
